/* Generated By:JavaCC: Do not edit this line. SMLCompilerConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SMLCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PREFIX = 6;
  /** RegularExpression Id. */
  int CREATE = 7;
  /** RegularExpression Id. */
  int VIEW = 8;
  /** RegularExpression Id. */
  int AS = 9;
  /** RegularExpression Id. */
  int CONSTRUCT = 10;
  /** RegularExpression Id. */
  int WITH = 11;
  /** RegularExpression Id. */
  int STR = 12;
  /** RegularExpression Id. */
  int CONCAT = 13;
  /** RegularExpression Id. */
  int BNODE = 14;
  /** RegularExpression Id. */
  int URI = 15;
  /** RegularExpression Id. */
  int PLAINLITERAL = 16;
  /** RegularExpression Id. */
  int TYPEDLITERAL = 17;
  /** RegularExpression Id. */
  int URLENCODE = 18;
  /** RegularExpression Id. */
  int OPENPAREN = 19;
  /** RegularExpression Id. */
  int CLOSEPAREN = 20;
  /** RegularExpression Id. */
  int OPENBRACE = 21;
  /** RegularExpression Id. */
  int CLOSEBRACE = 22;
  /** RegularExpression Id. */
  int QUESTIONMARK = 23;
  /** RegularExpression Id. */
  int SEMICOLON = 24;
  /** RegularExpression Id. */
  int DOT = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int COLON = 27;
  /** RegularExpression Id. */
  int ASSIGN = 28;
  /** RegularExpression Id. */
  int STRING = 29;
  /** RegularExpression Id. */
  int IDENT = 30;
  /** RegularExpression Id. */
  int LETTER = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;
  /** RegularExpression Id. */
  int NUMBER = 33;
  /** RegularExpression Id. */
  int VARIAVEL = 34;
  /** RegularExpression Id. */
  int ENDERECO = 35;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 36;
  /** RegularExpression Id. */
  int INVALID_CONST = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"PREFIX\"",
    "\"CREATE\"",
    "\"VIEW\"",
    "\"As\"",
    "\"Construct\"",
    "\"WITH\"",
    "\"str\"",
    "\"concat\"",
    "\"bnode\"",
    "\"uri\"",
    "\"plainLiteral\"",
    "\"typedLiteral\"",
    "\"urlEncode\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"?\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\"=\"",
    "<STRING>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<VARIAVEL>",
    "<ENDERECO>",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
